export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_RESET = 'CATEGORY_RESET'


export const CATEGORY_GET_FAIL = 'CATEGORY_GET_FAIL'
export const CATEGORY_GET_REQUEST = 'CATEGORY_GET_REQUEST'
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS'

export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'

export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'

export const CATEGORY_GET_HOME_REQUEST = 'CATEGORY_GET_HOME_REQUEST'
export const CATEGORY_GET_HOME_SUCCESS = 'CATEGORY_GET_HOME_SUCCESS'
export const CATEGORY_GET_HOME_FAIL = 'CATEGORY_GET_HOME_FAIL'

export const GET_SINGLE_CATEGORY_PRODUCTS_SUCCESS = 'GET_SINGLE_CATEGORY_PRODUCTS_SUCCESS'
export const GET_SINGLE_CATEGORY_PRODUCTS_FAIL = 'GET_SINGLE_CATEGORY_PRODUCTS_FAIL'
export const GET_SINGLE_CATEGORY_PRODUCTS_REQUEST = 'GET_SINGLE_CATEGORY_PRODUCTS_REQUEST'


export const HOME_CATEGORY_CREATE_REQUEST = 'HOME_CATEGORY_CREATE_REQUEST'
export const HOME_CATEGORY_CREATE_FAIL = 'HOME_CATEGORY_CREATE_FAIL'
export const HOME_CATEGORY_CREATE_SUCCESS = 'HOME_CATEGORY_CREATE_SUCCESS'