export const ADD_TO_CARD_REQUEST = 'ADD_TO_CARD_REQUEST'
export const ADD_TO_CARD_SUCCESS = 'ADD_TO_CARD_SUCCESS'
export const ADD_TO_CARD_FAIL = 'ADD_TO_CARD_FAIL'

export const ADD_TO_DELETE_ITEM = 'ADD_TO_DELETE_ITEM';
export const ADD_TO_SHIPPING_ITEM = 'ADD_TO_SHIPPING_ITEM'


export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const GET_SECRIT_KEY_REQUEST = 'GET_SECRIT_KEY_REQUEST'
export const GET_SECRIT_KEY_SUCCESS = 'GET_SECRIT_KEY_SUCCESS'
export const GET_SECRIT_KEY_FAIL = 'GET_SECRIT_KEY_FAIL'

export const GET_ALL_USER_ORDER_REQUEST = 'GET_ALL_USER_ORDER_REQUEST'
export const GET_ALL_USER_ORDER_SUCCESS = 'GET_ALL_USER_ORDER_SUCCESS'
export const GET_ALL_USER_ORDER_FAIL = 'GET_ALL_USER_ORDER_SUCCESS'

export const ORDER_STATUS_UPDATE_USER_REQUEST = 'ORDER_STATUS_UPDATE_USER_REQUEST'
export const ORDER_STATUS_UPDATE_USER_SUCCESS = 'ORDER_STATUS_UPDATE_USER_SUCCESS'
export const ORDER_STATUS_UPDATE_USER_FAIL = 'ORDER_STATUS_UPDATE_USER_FAIL'
export const ORDER_STATUS_UPDATE_USER_RESET = 'ORDER_STATUS_UPDATE_USER_RESET'