export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const CREATE_PRODUCT_REST = 'CREATE_PRODUCT_REST';



export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST'
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS'
export const GET_ADMIN_PRODUCTS_FAIL = 'GET_ADMIN_PRODUCTS_FAIL'


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'

export const PRODUCT_SINGLE_FAIL = 'PRODUCT_SINGLE_FAIL'
export const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS'
export const PRODUCT_SINGLE_REQUEST = 'PRODUCT_SINGLE_REQUEST'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const GET_PRODUCTS_CATEGORY_REQUEST = 'GET_PRODUCTS_CATEGORY_REQUEST'
export const GET_PRODUCTS_CATEGORY_SUCCESS = 'GET_PRODUCTS_CATEGORY_SUCCESS'
export const GET_PRODUCTS_CATEGORY_FAIL = 'GET_PRODUCTS_CATEGORY_FAIL'


export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST'
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS'
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL'
export const PRODUCT_REVIEW_RESET = 'PRODUCT_REVIEW_RESET'

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'

export const GET_HOME_CATEGORY_SUCCESS = 'GET_HOME_CATEGORY_SUCCESS'
export const GET_HOME_CATEGORY_REQUEST = 'GET_HOME_CATEGORY_REQUEST'
export const GET_HOME_CATEGORY_FAIL = 'GET_HOME_CATEGORY_FAIL'

export const GET_OFFER_GL_PRODUCTS_FAIL = 'GET_OFFER_GL_PRODUCTS_FAIL'
export const GET_OFFER_GL_PRODUCTS_REQUEST = 'GET_OFFER_GL_PRODUCTS_REQUEST'
export const GET_OFFER_GL_PRODUCTS_SUCCESS = 'GET_OFFER_GL_PRODUCTS_SUCCESS'

export const GET_HOME_UNIQUE_PRODUCTS_SUCCESS = 'GET_HOME_UNIQUE_PRODUCTS_SUCCESS'
export const GET_HOME_UNIQUE_PRODUCTS_FAIL = 'GET_HOME_UNIQUE_PRODUCTS_FAIL'
export const GET_HOME_UNIQUE_PRODUCTS_REQUEST = 'GET_HOME_UNIQUE_PRODUCTS_REQUEST'


export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST'
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS'
export const CREATE_BANNER_FAIL = 'CREATE_BANNER_FAIL'
export const BANNER_RESET = 'BANNER_RESET'

export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS'
export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST'
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL'