export const REGISTER_CREATE_REQUEST = 'REGISTER_CREATE_REQUEST'
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS'
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL'
export const REGISTER_RESET = 'REGISTER_RESET'

export const REGISTER_OTP_REQUEST = 'REGISTER_OTP_REQUEST'
export const REGISTER_OTP_SUCCESS = 'REGISTER_OTP_SUCCESS'
export const REGISTER_OTP_FAIL = 'REGISTER_OTP_FAIL'


export const LOGHIN_CREATE_REQUEST = 'LOGHIN_CREATE_REQUEST'
export const LOGHIN_CREATE_SUCCESS = 'LOGHIN_CREATE_SUCCESS'
export const LOGHIN_CREATE_FAIL = 'LOGHIN_CREATE_FAIL'


export const  LOGHIN_RESET = 'LOGHIN_RESET'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const  GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'
export const  GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const  GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'

export const  CREATE_PERMISSION_REQUEST = 'CREATE_PERMISSION_REQUEST'
export const  CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS'
export const  CREATE_PERMISSION_FAIL = 'CREATE_PERMISSION_FAIL'
export const  ADMIN_USER_RESET = 'ADMIN_USER_RESET'

export const  ADMIN_PROFILE_UPDATE_REQUEST = 'ADMIN_PROFILE_UPDATE_REQUEST'
export const  ADMIN_PROFILE_UPDATE_SUCCESS = 'ADMIN_PROFILE_UPDATE_SUCCESS'
export const  ADMIN_PROFILE_UPDATE_FAIL = 'ADMIN_PROFILE_UPDATE_FAIL'
export const  ADMIN_PROFILE_RESET = 'ADMIN_PROFILE_RESET'